name: CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
      - 'Dockerfile'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.go'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go version

      - run: go mod tidy
      - run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go version

#      - name: Install GStreamer dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y gstreamer1.0-tools gstreamer1.0-plugins-base \
#          gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
#          libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev pkg-config

      - name: Run tests
        run: go test -race -count 1 -p 8 -parallel 8 -timeout 1m -coverpkg ./... -coverprofile coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}