name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
      - 'Dockerfile'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.go'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v2.1.6
          args: --timeout 10m

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true

#      - name: Install GStreamer dependencies
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y gstreamer1.0-tools gstreamer1.0-plugins-base \
#          gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
#          libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev pkg-config

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
